#!/bin/bash
#author : yunusem, hikmet
RED='\033[1;31m'
YEL='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${RED}$0" >> /tmp/eta_log
u=`/usr/bin/whoami`
echo -e "${RED}$0 ${NC}running as ${YEL}$u" >> /tmp/eta_log
removed=`rm -rvf /tmp/optic_touch.pid`
echo -e "${RED}$0 ${YEL}$removed" >> /tmp/eta_log

START=0
SUCCESS=0
FAIL=0

contains() {
    string="$1"
    substring="$2"
    if test "${string#*$substring}" != "$string"; then
        return 0    # $substring is in $string
    else
        return 1    # $substring is not in $string
    fi
}


first_run() {
    echo -e "${RED}$0${NC} :starting first run" >> /tmp/eta_log
    while read line ; do

        if contains "$line" "input:   Optical TouchScreen"; then
            echo -e "${RED}$0${NC} :input tag detected START=1 FAIL=0 SUCCESS=0" >> /tmp/eta_log
            START=1
            FAIL=0
            SUCCESS=0
        fi

        if contains "$line" "ODT id=0xc20: optictouch_probe success!"; then
            echo -e "${RED}$0${NC} :ODT id=0xc20 tag detected SUCCESS=1" >> /tmp/eta_log
            SUCCESS=1
        fi

        if contains "$line" "optictouch: ODT:"; then
            echo -e "${RED}$0${NC} :optictouch tag detected START=0 FAIL=1" >> /tmp/eta_log
            FAIL=1
            START=0
        fi

done < <(tail -7 /var/log/kern.log)


    if [ "$SUCCESS" -eq 1 ] && [ "$FAIL" -ne 1 ]
    then
        if [ "$START" -eq 1 ]
        then
            echo -e "${RED}$0${NC} :everything is ok finishing first loop" >> /tmp/eta_log
            SUCCESS=0
            FAIL=0
            START=0
            return 0
        fi
        echo -e "${RED}$0${NC} :everything is not ok calling second_run" >> /tmp/eta_log
        return 1
    fi
    return 1
}

second_run() {
    echo -e "${RED}$0${NC} :starting second run" >> /tmp/eta_log
    while read line ; do

        if contains "$line" "input:   Optical TouchScreen"; then
            echo -e "${RED}$0${NC} :input tag detected START=1 FAIL=0 SUCCESS=0" >> /tmp/eta_log
            START=1
            FAIL=0
            SUCCESS=0
        fi

        if contains "$line" "ODT id=0xc20: optictouch_probe success!"; then
            echo -e "${RED}$0${NC} :ODT id=0xc20 tag detected SUCCESS=1" >> /tmp/eta_log
            SUCCESS=1
        fi

        if contains "$line" "optictouch: ODT:"; then
            echo -e "${RED}$0${NC} :optictouch tag detected START=0 FAIL=1" >> /tmp/eta_log
            FAIL=1
            START=0
        fi

        if [ "$SUCCESS" -eq 1 ] && [ "$FAIL" -ne 1 ]
        then
            if [ "$START" -eq 1 ]
            then
                echo -e "${RED}$0${NC} :everything is ok breaking the loop" >> /tmp/eta_log
                SUCCESS=0
                FAIL=0
                START=0
                break
            fi
            echo -e "${RED}$0${NC} :everything is not ok continuing the loop" >> /tmp/eta_log
        fi
done < <(tail -fn0 /var/log/kern.log)
}


first_run_phase_2() {
    echo -e "${RED}$0${NC} :starting first run" >> /tmp/eta_log
    while read line ; do

        if contains "$line" "input: Optical Touchscreen"; then
            echo -e "${RED}$0${NC} :input tag detected SUCCESS=1 breaking the loop" >> /tmp/eta_log
            SUCCESS=1
            break
        fi
    done < <(tail -30 /var/log/kern.log)

    if [ "$SUCCESS" -eq 1 ]
    then
        echo -e "${RED}$0${NC} :everything is ok finishing first loop" >> /tmp/eta_log
        return 0
    fi
    echo -e "${RED}$0${NC} :something went wrong, cloud not detect the optictouch" >> /tmp/eta_log
    return 1
}



if lsusb | grep -qE "(2621:2201|2621:4501)" ; then
    echo -e "${RED}$0${NC} :The IWB is ${GREEN}PHASE 2" >> /tmp/eta_log
    if ! first_run_phase_2; then
        exit 1
    fi
elif lsusb | grep -qE "(6615:0084|6615:0085|6615:0086|6615:0087|6615:0088|6615:0c20)" ; then
    echo -e "${RED}$0${NC} :The IWB is ${GREEN}PHASE 1" >> /tmp/eta_log
    if ! first_run; then
        second_run
    fi
fi

echo -e "${RED}$0 ${NC}creating /tmp/optic_touch.pid" >> /tmp/eta_log
touch /tmp/optic_touch.pid
chmod 777 /tmp/optic_touch.pid

echo -e "${RED}$0 ${NC}driver ready, ${GREEN}done." >> /tmp/eta_log
