#!/bin/bash
#author : yunusem, hikmet

set -e

RED='\033[1;31m'
YEL='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${RED}$0" >> $LOG_FILE
u=`/usr/bin/whoami`
echo -e "${RED}$0${NC} : running as ${YEL}$u" >> $LOG_FILE

LOG_FILE=/var/eta.log
OPTICTOUCH_PID=/tmp/optictouch.pid

if [ -f $LOG_FILE ]; then
    echo -e "${RED}$0${NC} : creating log file ${YEL}$LOG_FILE" >> $LOG_FILE
    touch $LOG_FILE
    chmod 666 $LOG_FILE
fi

if [ -f $OPTICTOUCH_PID ];then
    removed=`rm -rvf $OPTICTOUCH_PID
    echo -e "${RED}$0${NC} : ${YEL}$removed" >> $LOG_FILE
fi


START=0
SUCCESS=0
FAIL=0


contains() {
    string="$1"
    substring="$2"
    if test "${string#*$substring}" != "$string"; then
        return 0    # $substring is in $string
    else
        return 1    # $substring is not in $string
    fi
}


while read line
do
    if contains "$line" "input:"; then
         if contains "$line" "Optical TouchScreen"; then
             echo -e "${RED}$0${NC} : input tag detected START=1 FAIL=0 SUCCESS=0" >> $LOG_FILE
             START=1
             FAIL=0
             SUCCESS=0
         fi

    elif contains "$line" "optictouch_probe success!"; then
         echo -e "${RED}$0${NC} : optictouch_probe sccuess tag detected SUCCESS=1" >> $LOG_FILE
         SUCCESS=1
    elif contains "$line" "optictouch:"; then
        if contains "$line" "ODT:"; then
            echo -e "${RED}$0${NC} : optictouch tag detected START=0 FAIL=1" >> $LOG_FILE
            FAIL=1
            START=0
            SUCCESS=0
            removed=`rm -rvf $OPTICTOUCH_PID
            echo -e "${RED}$0${NC} : ${YEL}$removed" >> $LOG_FILE
        fi
    fi

    if [ "$SUCCESS" -eq 1 ] && [ "$FAIL" -ne 1 ]; then
        if [ "$START" -eq 1 ]; then
            echo -e "${RED}$0${NC} : everything is ok" >> $LOG_FILE
            SUCCESS=0
            FAIL=0
            START=0
            echo -e "${RED}$0${NC} : creating optictouch.pid" >> $LOG_FILE
            touch OPTICTOUCH_PID
            chmod 777 OPTICTOUCH_PID
        fi
    fi
done < <(tail -1f $1)

