#!/bin/bash
#author : yunusem, hikmet

set -e

RED='\033[1;31m'
YEL='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

LOG_FILE=/var/log/eta.log
OPTICTOUCH_PID=/var/run/optictouch.pid
START=0
SUCCESS=0
FAIL=0

if [ ! -f $LOG_FILE ]; then
    touch $LOG_FILE
    chmod 666 $LOG_FILE
    echo -e "${RED}$0${NC} : creating log file ${YEL}$LOG_FILE" >> $LOG_FILE
fi

echo -e "${RED}$0" >> $LOG_FILE
u=$(/usr/bin/whoami)
echo -e "${RED}$0${NC} : running as ${YEL}$u" >> $LOG_FILE

remove_pid() {
    if [ -f $OPTICTOUCH_PID ];then
        removed=$(rm -rvf $OPTICTOUCH_PID)
        echo -e "${RED}$0${NC} : ${YEL}$removed" >> $LOG_FILE
    fi
}

create_pid() {
    echo -e "${RED}$0${NC} : creating ${YEL}$OPTICTOUCH_PID" >> $LOG_FILE
    touch $OPTICTOUCH_PID
    chmod 644 $OPTICTOUCH_PID
}

contains() {
    string="$1"
    substring="$2"
    if test "${string#*$substring}" != "$string"; then
        return 0    # $substring is in $string
    else
        return 1    # $substring is not in $string
    fi
}

handler_loop() {
    while read line
    do
        if contains "$line" "input:"; then
            if contains "$line" "Optical TouchScreen"; then
                echo -e "${RED}$0${NC} : input tag detected START = ${YEL}1${NC} FAIL = ${YEL}0${NC} SUCCESS = ${YEL}0${NC}" >> $LOG_FILE
                START=1
                FAIL=0
                SUCCESS=0
            fi
        elif contains "$line" "optictouch_probe success!"; then
            echo -e "${RED}$0${NC} : optictouch_probe success tag detected SUCCESS = ${YEL}1${NC}" >> $LOG_FILE
            SUCCESS=1
        elif contains "$line" "optictouch:"; then
            if contains "$line" "ODT:"; then
                echo -e "${RED}$0${NC} : optictouch tag detected START = ${YEL}0${NC} FAIL = ${YEL}1${NC} SUCCESS = ${YEL}0${NC}" >> $LOG_FILE
                FAIL=1
                START=0
                SUCCESS=0
                remove_pid
            fi
        fi

        if [ "$SUCCESS" -eq 1 ] && [ "$FAIL" -ne 1 ]; then
            if [ "$START" -eq 1 ]; then
                echo -e "${RED}$0${NC} : everything is ${GREEN}OK." >> $LOG_FILE
                SUCCESS=0
                FAIL=0
                START=0
                create_pid
            fi
        fi
    done < <(tail -100f /var/log/kern.log)
}

if lsusb | grep -qE "(2621:2201|2621:4501)" ; then
    echo -e "${RED}$0${NC} : The IWB is ${GREEN}PHASE 2" >> $LOG_FILE
    handler_loop
elif lsusb | grep -qE "(6615:0084|6615:0085|6615:0086|6615:0087|6615:0088|6615:0c20)" ; then
    echo -e "${RED}$0${NC} : The IWB is ${GREEN}PHASE 1" >> $LOG_FILE
    handler_loop
else
    create_pid
fi

