#!/bin/bash

#author : yunusem, hikmet

RED='\033[1;31m'
YEL='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

LOG_FILE=/var/log/eta.log
OPTICTOUCH_PID=/var/run/optictouch.pid

echo -e "${YEL}$0" >> $LOG_FILE
u=`/usr/bin/whoami`
echo -e "${YEL}$0 ${NC}running as ${YEL}$u" >> $LOG_FILE

FLAG="IDLE"

while true
do
    if [ ! -f $OPTICTOUCH_PID ]; then
        if [ "$FLAG" == "IDLE" ]; then
            echo -e "${YEL}$0${NC} : pid not found calling ${YEL}/usr/bin/eta-optictouch-busy &" >> $LOG_FILE
            /usr/bin/eta-optictouch-busy &
            FLAG="BUSY"
        fi
    else
        if [ "$FLAG" == "BUSY" ]; then
            echo -e "${YEL}$0${NC} : pid found terminating every ${YEL}eta-optictouch-busy" >> $LOG_FILE
            killall eta-optictouch-busy
            FLAG="IDLE"
        fi
    fi
    sleep 1
done
